# Generated by Django 5.1.2 on 2024-11-06 19:06

import django.db.models.deletion
import handbook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('number', models.CharField(max_length=10, unique=True, validators=[handbook.models.validate_section_number])),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number', models.CharField(editable=False, max_length=10, unique=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('policy_statements', models.TextField(blank=True, null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('procedures', models.TextField(blank=True, null=True)),
                ('policy_owner', models.CharField(choices=[('Executive', 'Executive'), ('Human Resources', 'Human Resources'), ('Business Development', 'Business Development'), ('Information Technology', 'Information Technology'), ('Finance', 'Finance'), ('Quality Management', 'Quality Management')], max_length=200)),
                ('version', models.CharField(max_length=10)),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('review_period', models.CharField(blank=True, max_length=50, null=True)),
                ('related_policies', models.ManyToManyField(blank=True, related_name='related_to', to='handbook.policy')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='handbook.policysection')),
            ],
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('definition', models.TextField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='handbook.policy')),
            ],
        ),
    ]
