# Generated by Django 5.1.2 on 2024-11-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definition',
            name='policy',
        ),
        migrations.AddField(
            model_name='policy',
            name='definitions',
            field=models.ManyToManyField(blank=True, related_name='policies', to='handbook.definition'),
        ),
    ]
